name: DnD CI

on:
  push:
    branches: [video]
  pull_request:
    branches: [video]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: dnd
      - name: Build
        run: yarn build
        working-directory: dnd
